### ISSUE TITLE
"Runtime babel is not supported!"

### ISSUE THREAD

**Issue by marclar** [serverless/serverless-runtime-babel#1]
Steps:
- `sls project create`
- `cd my-project`
- `npm install serverless-runtime-babel --save`
- `sls function create`

Screencast:

[![asciicast](https://asciinema.org/a/dak8ru6hzewkhnej99y5tfaau.png)](https://asciinema.org/a/dak8ru6hzewkhnej99y5tfaau)

**Comment by austencollins** [comment]
@marclar Thanks for the helpful video.  I'm having a bit of trouble recreating this.  Are you using the latest version of `v0.5` (just released, so you can npm install)?  And the latest version of the babel-runtime?

**Comment by marclar** [comment]
That's the least I could do :)

Yes, I updated and it's working now. Thank you...
