### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless-runtime-babel#2]
Just updated a project to 0.5 and used the babel runtime.

Here's a screenshot from the logs:
<img width="1199" alt="bildschirmfoto 2016-03-23 um 11 06 46" src="https://cloud.githubusercontent.com/assets/1606004/13982007/c9d67872-f0e7-11e5-9708-49a81a6298e7.png">

This line seems to cause the error:
https://github.com/serverless/serverless-runtime-babel/blob/master/lib/RuntimeBabel.js#L233

**Comment by pmuens** [comment]
Maybe https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.v4zd4fdgn has smth. todo with it. Babel depends on some of the affected packages. Not quite sure though.

This Babel PR resolves the issue: https://github.com/babel/babel/pull/3440

**Comment by pmuens** [comment]
Thanks!

**Comment by pmuens** [comment]
@ac360 Any chance that the fix get's uploaded to NPM?

**Comment by austencollins** [comment]
On it!

**Comment by austencollins** [comment]
Done

**Comment by pmuens** [comment]
Awesome! Thanks!
