### ISSUE TITLE
Env variable wrapper does not handle asynchronous "classic style" handlers correctly

### ISSUE THREAD

**Issue by grayrest** [serverless/serverless-runtime-babel#4]
If you have a handler that expects to return from lambda by calling `context.done()` in a callback:

``` js
    exports.handler = function(event, context) {
      setTimeout(function(){ context.succeed("yay"); }, 0);
    }
```

The current wrapper implementation will always return null because `context.succeed(result)` is called unconditionally and synchronously. Switching to:

``` js
                if (typeof result !== 'undefined') {
                  context.succeed(result);
                }
```

Solves the problem.

**Comment by minibikini** [comment]
Fixed. Thanks, @grayrest!
