### ISSUE TITLE
AWS SDK not bundled properly

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless-runtime-babel#5]
I'm facing the error that the `aws-sdk` is not bundled correctly.

Here's an example `handler.js` file which reproduces the bug:

```
'use strict';

var AWS = require('aws-sdk');

module.exports.handler = function(event, context) {
  event.dynamo = AWS.DynamoDB.DocumentClient({});

  return context.done(null, event);
};

```

When I upload this to AWS I get the error `Cannot call method 'DocumentClient' of undefined`.

It seems like `AWS` is not loaded at all.

Thanks for looking into this!

**Comment by minibikini** [comment]
Fixed. Thanks @pmuens!

**Comment by pmuens** [comment]
Awesome! Thanks @minibikini

**Comment by pmuens** [comment]
@ac360 this solves the issue we've discussed this morning / night.

Would be awesome if you could release this via NPM. Thanks in advance!
