### ISSUE TITLE
EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by marclar** [serverless/serverless-runtime-babel#9]
Steps:
1. `sls project create`
2. add `serverless-runtime-babel`
3. `sls function create`
4. `cd` to function directory
5. `npm init -f -y`
6. `npm install` babel plugins & presets for ES7 features
7. add babel plugins & presets to `s-function.json`
8. `sls function run` works
9. `sls function deploy` breaks

[![](https://i.imgur.com/fFkFvCc.png)](https://youtu.be/kEslaj1KyWM)

**Comment by martinbooth** [comment]
This will fix it: https://github.com/serverless/serverless-runtime-babel/pull/10
